// Code generated by protoc-gen-go.
// source: proto.pb
// DO NOT EDIT!

/*
Package mbproto is a generated protocol buffer package.

It is generated from these files:
	proto.pb

It has these top-level messages:
	RawMessage
	TransmitMessage
	HandshakeMessage
*/
package mbproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RawMessage struct {
	IV      []byte `protobuf:"bytes,1,opt,name=IV,proto3" json:"IV,omitempty"`
	Nonce   []byte `protobuf:"bytes,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Payload []byte `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (m *RawMessage) Reset()                    { *m = RawMessage{} }
func (m *RawMessage) String() string            { return proto.CompactTextString(m) }
func (*RawMessage) ProtoMessage()               {}
func (*RawMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TransmitMessage struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *TransmitMessage) Reset()                    { *m = TransmitMessage{} }
func (m *TransmitMessage) String() string            { return proto.CompactTextString(m) }
func (*TransmitMessage) ProtoMessage()               {}
func (*TransmitMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HandshakeMessage struct {
	NetworkKey []byte `protobuf:"bytes,1,opt,name=networkKey,proto3" json:"networkKey,omitempty"`
	PrivateIP  uint32 `protobuf:"varint,2,opt,name=privateIP" json:"privateIP,omitempty"`
}

func (m *HandshakeMessage) Reset()                    { *m = HandshakeMessage{} }
func (m *HandshakeMessage) String() string            { return proto.CompactTextString(m) }
func (*HandshakeMessage) ProtoMessage()               {}
func (*HandshakeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*RawMessage)(nil), "mbproto.RawMessage")
	proto.RegisterType((*TransmitMessage)(nil), "mbproto.TransmitMessage")
	proto.RegisterType((*HandshakeMessage)(nil), "mbproto.HandshakeMessage")
}

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2b, 0x48, 0x12, 0x62, 0xcf, 0x4d, 0x02, 0xb3, 0x95, 0x2c, 0xb8, 0xb8, 0x82, 0x12,
	0xcb, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0xb8, 0xb8, 0x98, 0x3c, 0xc3, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x78, 0x84, 0x78, 0xb9, 0x58, 0xfd, 0xf2, 0xf3, 0x92, 0x53, 0x25, 0x98, 0xc0,
	0x5c, 0x7e, 0x2e, 0xf6, 0x80, 0xc4, 0xca, 0x9c, 0xfc, 0xc4, 0x14, 0x09, 0x66, 0x90, 0x80, 0x92,
	0x12, 0x17, 0x7f, 0x48, 0x51, 0x62, 0x5e, 0x71, 0x6e, 0x66, 0x09, 0x4c, 0x3b, 0x50, 0x4d, 0x01,
	0x54, 0x0d, 0xd8, 0x0c, 0x25, 0x4b, 0x2e, 0x01, 0x8f, 0xc4, 0xbc, 0x94, 0xe2, 0x8c, 0xc4, 0xec,
	0x54, 0x98, 0x22, 0xa0, 0x25, 0x79, 0xa9, 0x25, 0xe5, 0xf9, 0x45, 0xd9, 0xde, 0xa9, 0x95, 0x50,
	0xbb, 0x04, 0xb9, 0x38, 0x0b, 0x8a, 0x32, 0xcb, 0x12, 0x4b, 0x52, 0x3d, 0x03, 0xc0, 0xf6, 0xf1,
	0x26, 0xb1, 0x81, 0xdd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xaa, 0xe8, 0xbe, 0xb4,
	0x00, 0x00, 0x00,
}
